spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      userService:
        timeoutDuration: 3s
